import {ColorTheme, SizeScale} from '../types/models';
import {
  ThemeColors,
  ThemePresetInfo,
  TypographyScale,
  SpacingScale,
  BorderRadiusScale,
  DimensionTokens,
  ElevationScale,
} from './types';

// ==========================================
// 1. Wallpaper Background Assets
// ==========================================

export const THEME_WALLPAPERS: Record<ColorTheme, any | null> = {
  ocean: null,
  green: null,
  rose: null,
  warm: null,
  blue: null,
  dark: null,
  midnightBloom: require('../assets/images/theme/theme-1.jpg'),
  sunsetWave: require('../assets/images/theme/theme-2.jpg'),
  auroraCyan: require('../assets/images/theme/theme-2.jpg'),
};

// ==========================================
// 2. Color Palettes by Theme & Appearance Mode
// ==========================================

export const THEME_PALETTES: Record<
  ColorTheme,
  {light: ThemeColors; dark: ThemeColors}
> = {
  ocean: {
    light: {
      primary: '#0284C7',
      primaryLight: '#E0F2FE',
      primaryDark: '#0369A1',
      secondary: '#0D9488',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#E2E8F0',
      borderSubtle: '#F1F5F9',
      shadow: '#0F172A',
      accent: '#38BDF8',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#38BDF8',
      primaryLight: '#082F49',
      primaryDark: '#0284C7',
      secondary: '#2DD4BF',
      background: '#0F172A',
      surface: '#1E293B',
      surfaceElevated: '#334155',
      card: '#1E293B',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#64748B',
      textInverse: '#0F172A',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#334155',
      borderSubtle: '#1E293B',
      shadow: '#000000',
      accent: '#0284C7',
      statusBar: 'light-content',
    },
  },
  green: {
    light: {
      primary: '#16A34A',
      primaryLight: '#DCFCE7',
      primaryDark: '#15803D',
      secondary: '#059669',
      background: '#F7FDF9',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#14342B',
      textSecondary: '#3F6256',
      textMuted: '#84A99C',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#D5E7DF',
      borderSubtle: '#EBF4F0',
      shadow: '#14342B',
      accent: '#4ADE80',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#4ADE80',
      primaryLight: '#052E16',
      primaryDark: '#16A34A',
      secondary: '#34D399',
      background: '#0A1E17',
      surface: '#14342B',
      surfaceElevated: '#1F473B',
      card: '#14342B',
      textPrimary: '#F7FDF9',
      textSecondary: '#C5DDD4',
      textMuted: '#6E9487',
      textInverse: '#0A1E17',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#1F473B',
      borderSubtle: '#14342B',
      shadow: '#000000',
      accent: '#16A34A',
      statusBar: 'light-content',
    },
  },
  rose: {
    light: {
      primary: '#E11D48',
      primaryLight: '#FFE4E6',
      primaryDark: '#BE123C',
      secondary: '#DB2777',
      background: '#FFF1F2',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#3B0715',
      textSecondary: '#6A2336',
      textMuted: '#A86C7C',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#FECDD3',
      borderSubtle: '#FFF1F2',
      shadow: '#3B0715',
      accent: '#FB7185',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#FB7185',
      primaryLight: '#4C0519',
      primaryDark: '#E11D48',
      secondary: '#F472B6',
      background: '#2B040F',
      surface: '#430919',
      surfaceElevated: '#5E1025',
      card: '#430919',
      textPrimary: '#FFF1F2',
      textSecondary: '#FECDD3',
      textMuted: '#9F4F64',
      textInverse: '#2B040F',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#5E1025',
      borderSubtle: '#430919',
      shadow: '#000000',
      accent: '#E11D48',
      statusBar: 'light-content',
    },
  },
  warm: {
    light: {
      primary: '#EA580C',
      primaryLight: '#FFEDD5',
      primaryDark: '#C2410C',
      secondary: '#D97706',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#2B1408',
      textSecondary: '#5C3823',
      textMuted: '#A37D66',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#FED7AA',
      borderSubtle: '#FFF7ED',
      shadow: '#2B1408',
      accent: '#FB923C',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#FB923C',
      primaryLight: '#431407',
      primaryDark: '#EA580C',
      secondary: '#FBBF24',
      background: '#1C0B04',
      surface: '#33160A',
      surfaceElevated: '#4A2312',
      card: '#33160A',
      textPrimary: '#FFFBF5',
      textSecondary: '#FED7AA',
      textMuted: '#9B6F55',
      textInverse: '#1C0B04',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#4A2312',
      borderSubtle: '#33160A',
      shadow: '#000000',
      accent: '#EA580C',
      statusBar: 'light-content',
    },
  },
  blue: {
    light: {
      primary: '#2563EB',
      primaryLight: '#DBEAFE',
      primaryDark: '#1D4ED8',
      secondary: '#4F46E5',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#0F172A',
      textSecondary: '#334155',
      textMuted: '#64748B',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#CBD5E1',
      borderSubtle: '#F1F5F9',
      shadow: '#0F172A',
      accent: '#60A5FA',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#60A5FA',
      primaryLight: '#172554',
      primaryDark: '#2563EB',
      secondary: '#818CF8',
      background: '#0B132B',
      surface: '#172554',
      surfaceElevated: '#1E3A8A',
      card: '#172554',
      textPrimary: '#F8FAFC',
      textSecondary: '#BFDBFE',
      textMuted: '#60A5FA',
      textInverse: '#0B132B',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#1E3A8A',
      borderSubtle: '#172554',
      shadow: '#000000',
      accent: '#2563EB',
      statusBar: 'light-content',
    },
  },
  dark: {
    light: {
      primary: '#0F172A',
      primaryLight: '#F1F5F9',
      primaryDark: '#020617',
      secondary: '#334155',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#CBD5E1',
      borderSubtle: '#E2E8F0',
      shadow: '#0F172A',
      accent: '#64748B',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#F8FAFC',
      primaryLight: '#1E293B',
      primaryDark: '#E2E8F0',
      secondary: '#94A3B8',
      background: '#090D16',
      surface: '#151C2C',
      surfaceElevated: '#1F293D',
      card: '#151C2C',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#64748B',
      textInverse: '#090D16',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#2A364F',
      borderSubtle: '#1A2338',
      shadow: '#000000',
      accent: '#94A3B8',
      statusBar: 'light-content',
    },
  },
  midnightBloom: {
    light: {
      primary: '#1E40AF',
      primaryLight: '#DBEAFE',
      primaryDark: '#172554',
      secondary: '#0284C7',
      background: '#F0F4F8',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: 'rgba(255, 255, 255, 0.94)',
      textPrimary: '#0A0E27',
      textSecondary: '#334155',
      textMuted: '#64748B',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#CBD5E1',
      borderSubtle: '#E2E8F0',
      shadow: '#0A0E27',
      accent: '#3B82F6',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#60A5FA',
      primaryLight: '#172554',
      primaryDark: '#3B82F6',
      secondary: '#38BDF8',
      background: '#060814',
      surface: 'rgba(15, 23, 42, 0.88)',
      surfaceElevated: 'rgba(30, 41, 59, 0.92)',
      card: 'rgba(15, 23, 42, 0.88)',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#94A3B8',
      textInverse: '#060814',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#1E293B',
      borderSubtle: '#0F172A',
      shadow: '#000000',
      accent: '#818CF8',
      statusBar: 'light-content',
    },
  },
  sunsetWave: {
    light: {
      primary: '#D97706',
      primaryLight: '#FEF3C7',
      primaryDark: '#B45309',
      secondary: '#E11D48',
      background: '#FFFDF5',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: 'rgba(255, 255, 255, 0.94)',
      textPrimary: '#1E293B',
      textSecondary: '#475569',
      textMuted: '#854D0E',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#FDE68A',
      borderSubtle: '#FEF3C7',
      shadow: '#1E293B',
      accent: '#0284C7',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#FBBF24',
      primaryLight: '#451A03',
      primaryDark: '#F59E0B',
      secondary: '#FB7185',
      background: '#0B161E',
      surface: 'rgba(17, 34, 46, 0.88)',
      surfaceElevated: 'rgba(28, 52, 70, 0.92)',
      card: 'rgba(17, 34, 46, 0.88)',
      textPrimary: '#FFFBEB',
      textSecondary: '#E2E8F0',
      textMuted: '#94A3B8',
      textInverse: '#0B161E',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#24455C',
      borderSubtle: '#142735',
      shadow: '#000000',
      accent: '#38BDF8',
      statusBar: 'light-content',
    },
  },
  auroraCyan: {
    light: {
      primary: '#0284C7',
      primaryLight: '#E0F2FE',
      primaryDark: '#0369A1',
      secondary: '#8B5CF6',
      background: '#F0F9FF',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: 'rgba(255, 255, 255, 0.94)',
      textPrimary: '#0F172A',
      textSecondary: '#334155',
      textMuted: '#64748B',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#BAE6FD',
      borderSubtle: '#E0F2FE',
      shadow: '#0F172A',
      accent: '#F59E0B',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#38BDF8',
      primaryLight: '#082F49',
      primaryDark: '#0284C7',
      secondary: '#C084FC',
      background: '#0A1924',
      surface: 'rgba(14, 30, 44, 0.88)',
      surfaceElevated: 'rgba(24, 48, 68, 0.92)',
      card: 'rgba(14, 30, 44, 0.88)',
      textPrimary: '#F0FDF4',
      textSecondary: '#BAE6FD',
      textMuted: '#64748B',
      textInverse: '#0A1924',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#1E3E58',
      borderSubtle: '#112536',
      shadow: '#000000',
      accent: '#FBBF24',
      statusBar: 'light-content',
    },
  },
};

// ==========================================
// 3. Preset Theme Catalog Metadata
// ==========================================

export const THEME_PRESETS: ThemePresetInfo[] = [
  {
    id: 'midnightBloom',
    label: 'Midnight Bloom',
    subtitle: 'Sculptural Velvet Navy & Ice Blue glow',
    category: 'wallpaper',
    wallpaper: THEME_WALLPAPERS.midnightBloom,
    palettePreview: ['#1E40AF', '#38BDF8', '#818CF8', '#060814'],
  },
  {
    id: 'sunsetWave',
    label: 'Sunset Wave',
    subtitle: 'Amber Dunes, Sunset Coral & Ocean Wave',
    category: 'wallpaper',
    wallpaper: THEME_WALLPAPERS.sunsetWave,
    palettePreview: ['#F59E0B', '#FB7185', '#38BDF8', '#0B161E'],
  },
  {
    id: 'auroraCyan',
    label: 'Aurora Flow',
    subtitle: 'Luminous Cyan, Orchid Lilac & Dusk',
    category: 'wallpaper',
    wallpaper: THEME_WALLPAPERS.auroraCyan,
    palettePreview: ['#0284C7', '#8B5CF6', '#FBBF24', '#0A1924'],
  },
  {
    id: 'warm',
    label: 'Warm Amber',
    subtitle: 'Cozy tangerine & warm earth tones',
    category: 'solid',
    wallpaper: null,
    palettePreview: ['#EA580C', '#D97706', '#FB923C', '#FFFBF5'],
  },
  {
    id: 'ocean',
    label: 'Ocean Teal',
    subtitle: 'Calming cerulean & seafoam greens',
    category: 'solid',
    wallpaper: null,
    palettePreview: ['#0284C7', '#0D9488', '#38BDF8', '#F8FAFC'],
  },
  {
    id: 'green',
    label: 'Emerald Green',
    subtitle: 'Nature greens with high-contrast legibility',
    category: 'solid',
    wallpaper: null,
    palettePreview: ['#16A34A', '#059669', '#4ADE80', '#F7FDF9'],
  },
  {
    id: 'rose',
    label: 'Rose Crimson',
    subtitle: 'Soft pink & deep crimson rose',
    category: 'solid',
    wallpaper: null,
    palettePreview: ['#E11D48', '#DB2777', '#FB7185', '#FFF1F2'],
  },
  {
    id: 'blue',
    label: 'Royal Blue',
    subtitle: 'Classic dependable blue & indigo',
    category: 'solid',
    wallpaper: null,
    palettePreview: ['#2563EB', '#4F46E5', '#60A5FA', '#F8FAFC'],
  },
  {
    id: 'dark',
    label: 'Slate Charcoal',
    subtitle: 'Minimalist slate & neutral monochrome',
    category: 'solid',
    wallpaper: null,
    palettePreview: ['#0F172A', '#334155', '#94A3B8', '#F8FAFC'],
  },
];

// ==========================================
// 4. Typography Scales (Large & Extra Large)
// ==========================================

export const TYPOGRAPHY_TOKENS: Record<SizeScale, TypographyScale> = {
  large: {
    heading1: {fontSize: 32, lineHeight: 40, fontWeight: '700'},
    heading2: {fontSize: 24, lineHeight: 32, fontWeight: '700'},
    body: {fontSize: 18, lineHeight: 26, fontWeight: '400'},
    caption: {fontSize: 14, lineHeight: 20, fontWeight: '500'},
    button: {fontSize: 18, lineHeight: 24, fontWeight: '600'},
  },
  extraLarge: {
    heading1: {fontSize: 40, lineHeight: 48, fontWeight: '800'},
    heading2: {fontSize: 30, lineHeight: 38, fontWeight: '700'},
    body: {fontSize: 22, lineHeight: 30, fontWeight: '500'},
    caption: {fontSize: 17, lineHeight: 24, fontWeight: '600'},
    button: {fontSize: 22, lineHeight: 28, fontWeight: '700'},
  },
};

// ==========================================
// 3. Spacing Scale
// ==========================================

export const SPACING_TOKENS: SpacingScale = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

// ==========================================
// 4. Border Radius Scale
// ==========================================

export const BORDER_RADIUS_TOKENS: BorderRadiusScale = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  round: 9999,
};

// ==========================================
// 5. Dimension Tokens (Sized for Accessibility)
// ==========================================

export const DIMENSION_TOKENS: Record<SizeScale, DimensionTokens> = {
  large: {
    buttonHeight: 56,
    iconSize: 32,
    avatarSize: 64,
    minTouchTarget: 48,
  },
  extraLarge: {
    buttonHeight: 68,
    iconSize: 44,
    avatarSize: 80,
    minTouchTarget: 56,
  },
};

// ==========================================
// 6. Elevation & Shadow Scales (Modern CSS boxShadow)
// ==========================================

export const ELEVATION_TOKENS: ElevationScale = {
  none: {},
  low: {
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.08)',
  },
  medium: {
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.12)',
  },
  high: {
    boxShadow: '0px 8px 24px rgba(0, 0, 0, 0.18)',
  },
};
