import {ColorTheme, SizeScale} from '../types/models';
import {
  ThemeColors,
  TypographyScale,
  SpacingScale,
  BorderRadiusScale,
  DimensionTokens,
  ElevationScale,
} from './types';

// ==========================================
// 1. Color Palettes by Theme & Appearance Mode
// ==========================================

export const THEME_PALETTES: Record<
  ColorTheme,
  {light: ThemeColors; dark: ThemeColors}
> = {
  ocean: {
    light: {
      primary: '#0284C7',
      primaryLight: '#E0F2FE',
      primaryDark: '#0369A1',
      secondary: '#0D9488',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#E2E8F0',
      borderSubtle: '#F1F5F9',
      shadow: '#0F172A',
      accent: '#38BDF8',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#38BDF8',
      primaryLight: '#082F49',
      primaryDark: '#0284C7',
      secondary: '#2DD4BF',
      background: '#0F172A',
      surface: '#1E293B',
      surfaceElevated: '#334155',
      card: '#1E293B',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#64748B',
      textInverse: '#0F172A',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#334155',
      borderSubtle: '#1E293B',
      shadow: '#000000',
      accent: '#0284C7',
      statusBar: 'light-content',
    },
  },
  green: {
    light: {
      primary: '#16A34A',
      primaryLight: '#DCFCE7',
      primaryDark: '#15803D',
      secondary: '#059669',
      background: '#F7FDF9',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#14342B',
      textSecondary: '#3F6256',
      textMuted: '#84A99C',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#D5E7DF',
      borderSubtle: '#EBF4F0',
      shadow: '#14342B',
      accent: '#4ADE80',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#4ADE80',
      primaryLight: '#052E16',
      primaryDark: '#16A34A',
      secondary: '#34D399',
      background: '#0A1E17',
      surface: '#14342B',
      surfaceElevated: '#1F473B',
      card: '#14342B',
      textPrimary: '#F7FDF9',
      textSecondary: '#C5DDD4',
      textMuted: '#6E9487',
      textInverse: '#0A1E17',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#1F473B',
      borderSubtle: '#14342B',
      shadow: '#000000',
      accent: '#16A34A',
      statusBar: 'light-content',
    },
  },
  rose: {
    light: {
      primary: '#E11D48',
      primaryLight: '#FFE4E6',
      primaryDark: '#BE123C',
      secondary: '#DB2777',
      background: '#FFF1F2',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#3B0715',
      textSecondary: '#6A2336',
      textMuted: '#A86C7C',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#FECDD3',
      borderSubtle: '#FFF1F2',
      shadow: '#3B0715',
      accent: '#FB7185',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#FB7185',
      primaryLight: '#4C0519',
      primaryDark: '#E11D48',
      secondary: '#F472B6',
      background: '#2B040F',
      surface: '#430919',
      surfaceElevated: '#5E1025',
      card: '#430919',
      textPrimary: '#FFF1F2',
      textSecondary: '#FECDD3',
      textMuted: '#9F4F64',
      textInverse: '#2B040F',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#5E1025',
      borderSubtle: '#430919',
      shadow: '#000000',
      accent: '#E11D48',
      statusBar: 'light-content',
    },
  },
  warm: {
    light: {
      primary: '#EA580C',
      primaryLight: '#FFEDD5',
      primaryDark: '#C2410C',
      secondary: '#D97706',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#2B1408',
      textSecondary: '#5C3823',
      textMuted: '#A37D66',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#FED7AA',
      borderSubtle: '#FFF7ED',
      shadow: '#2B1408',
      accent: '#FB923C',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#FB923C',
      primaryLight: '#431407',
      primaryDark: '#EA580C',
      secondary: '#FBBF24',
      background: '#1C0B04',
      surface: '#33160A',
      surfaceElevated: '#4A2312',
      card: '#33160A',
      textPrimary: '#FFFBF5',
      textSecondary: '#FED7AA',
      textMuted: '#9B6F55',
      textInverse: '#1C0B04',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#4A2312',
      borderSubtle: '#33160A',
      shadow: '#000000',
      accent: '#EA580C',
      statusBar: 'light-content',
    },
  },
  blue: {
    light: {
      primary: '#2563EB',
      primaryLight: '#DBEAFE',
      primaryDark: '#1D4ED8',
      secondary: '#4F46E5',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#0F172A',
      textSecondary: '#334155',
      textMuted: '#64748B',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#CBD5E1',
      borderSubtle: '#F1F5F9',
      shadow: '#0F172A',
      accent: '#60A5FA',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#60A5FA',
      primaryLight: '#172554',
      primaryDark: '#2563EB',
      secondary: '#818CF8',
      background: '#0B132B',
      surface: '#172554',
      surfaceElevated: '#1E3A8A',
      card: '#172554',
      textPrimary: '#F8FAFC',
      textSecondary: '#BFDBFE',
      textMuted: '#60A5FA',
      textInverse: '#0B132B',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#1E3A8A',
      borderSubtle: '#172554',
      shadow: '#000000',
      accent: '#2563EB',
      statusBar: 'light-content',
    },
  },
  dark: {
    light: {
      primary: '#0F172A',
      primaryLight: '#F1F5F9',
      primaryDark: '#020617',
      secondary: '#334155',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      card: '#FFFFFF',
      textPrimary: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#94A3B8',
      textInverse: '#FFFFFF',
      success: '#16A34A',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      border: '#CBD5E1',
      borderSubtle: '#E2E8F0',
      shadow: '#0F172A',
      accent: '#64748B',
      statusBar: 'dark-content',
    },
    dark: {
      primary: '#F8FAFC',
      primaryLight: '#1E293B',
      primaryDark: '#E2E8F0',
      secondary: '#94A3B8',
      background: '#090D16',
      surface: '#151C2C',
      surfaceElevated: '#1F293D',
      card: '#151C2C',
      textPrimary: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#64748B',
      textInverse: '#090D16',
      success: '#4ADE80',
      successLight: '#052E16',
      error: '#F87171',
      errorLight: '#450A0A',
      warning: '#FBBF24',
      warningLight: '#451A03',
      border: '#2A364F',
      borderSubtle: '#1A2338',
      shadow: '#000000',
      accent: '#94A3B8',
      statusBar: 'light-content',
    },
  },
};

// ==========================================
// 2. Typography Scales (Large & Extra Large)
// ==========================================

export const TYPOGRAPHY_TOKENS: Record<SizeScale, TypographyScale> = {
  large: {
    heading1: {fontSize: 32, lineHeight: 40, fontWeight: '700'},
    heading2: {fontSize: 24, lineHeight: 32, fontWeight: '700'},
    body: {fontSize: 18, lineHeight: 26, fontWeight: '400'},
    caption: {fontSize: 14, lineHeight: 20, fontWeight: '500'},
    button: {fontSize: 18, lineHeight: 24, fontWeight: '600'},
  },
  extraLarge: {
    heading1: {fontSize: 40, lineHeight: 48, fontWeight: '800'},
    heading2: {fontSize: 30, lineHeight: 38, fontWeight: '700'},
    body: {fontSize: 22, lineHeight: 30, fontWeight: '500'},
    caption: {fontSize: 17, lineHeight: 24, fontWeight: '600'},
    button: {fontSize: 22, lineHeight: 28, fontWeight: '700'},
  },
};

// ==========================================
// 3. Spacing Scale
// ==========================================

export const SPACING_TOKENS: SpacingScale = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

// ==========================================
// 4. Border Radius Scale
// ==========================================

export const BORDER_RADIUS_TOKENS: BorderRadiusScale = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  round: 9999,
};

// ==========================================
// 5. Dimension Tokens (Sized for Accessibility)
// ==========================================

export const DIMENSION_TOKENS: Record<SizeScale, DimensionTokens> = {
  large: {
    buttonHeight: 56,
    iconSize: 32,
    avatarSize: 64,
    minTouchTarget: 48,
  },
  extraLarge: {
    buttonHeight: 68,
    iconSize: 44,
    avatarSize: 80,
    minTouchTarget: 56,
  },
};

// ==========================================
// 6. Elevation & Shadow Scales
// ==========================================

export const ELEVATION_TOKENS: ElevationScale = {
  none: {
    shadowColor: 'transparent',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  low: {
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  high: {
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 8,
  },
};
